### ISSUE TITLE
Table representation 

### ISSUE THREAD

**Issue by jessebrown8895** [learn-co-curriculum/phase-3-sql-table-relations-creating-join-tables#1]
### Canvas Link

https://learning.flatironschool.com/courses/4697/pages/creating-join-tables?module_item_id=287367

### Concern

I believe this lesson is hard to understand because we do not have a visual representation of the tables. Therefore, we cannot see any numbers that match up to what cats and what numbers match up to what owners to create the many-to-many relationship.

### Suggested Changes

Give us a visual table representation of the owners, cats and owners table to references

**Comment by lizbur10** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in
upcoming releases of this curriculum.

As always, thanks for contributing! 💙
